### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Rinvay616** [WheelChan/Multi-Agent-Path-Finding#1]
how to call sipp_astar

**Comment by Sirius-1110** [comment]
```python
python run_experiments.py --instance instances/test1.txt --solver Sipp_independent
***Import an instance***
Start locations
@ @ @ @ @ 
@ . . 1 @ 
@ . . . @ 
@ . . . @ 
@ . . . @ 
@ . . 0 @ 
@ @ @ @ @ 

Goal locations
@ @ @ @ @ 
@ . . 0 @ 
@ . . . @ 
@ . . . @ 
@ . . . @ 
@ . 1 . @ 
@ @ @ @ @ 

***Run SIPP Independent***
Inside SIPP start finding a soln!!!!

Plan successfully calculated!!
Expanded Nodes:  4
Generated Nodes:  7
!!!! PLAN: 
[{'x': 5, 'y': 3, 't': 0}, {'x': 4, 'y': 3, 't': 1}, {'x': 3, 'y': 3, 't': 2}, {'x': 2, 'y': 3, 't': 3}, {'x': 1, 'y': 3, 't': 4}]
[[{'x': 5, 'y': 3, 't': 0}, {'x': 4, 'y': 3, 't': 1}, {'x': 3, 'y': 3, 't': 2}, {'x': 2, 'y': 3, 't': 3}, {'x': 1, 'y': 3, 't': 4}]]
Inside SIPP start finding a soln!!!!

Traceback (most recent call last):
  File "run_experiments.py", line 122, in <module>
    paths = solver.find_solution()
  File "/home/XX/Documents/Multi-Agent-Path-Finding/sipp_independent.py", line 61, in find_solution
    raise BaseException('No solutions')
BaseException: No solutions
```
